//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ArticleName { get; set; }
        public string ArticleText { get; set; }
        public Nullable<int> ArticleCategoryID { get; set; }
        public Nullable<int> ArticleStatusID { get; set; }
    
        public virtual ArticleCategory ArticleCategory { get; set; }
        public virtual User User { get; set; }
    }
}
