//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Fuels = new HashSet<Fuel>();
            this.Issues = new HashSet<Issue>();
            this.Maintenances = new HashSet<Maintenance>();
            this.Notes = new HashSet<Note>();
            this.OdometerHistories = new HashSet<OdometerHistory>();
            this.Projects = new HashSet<Project>();
        }
    
        public int CarID { get; set; }
        public int UserID { get; set; }
        public string Nickname { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string TrimLevel { get; set; }
        public string Comments { get; set; }
        public string Engine { get; set; }
        public string Transmission { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> MilesAtPurchase { get; set; }
        public Nullable<int> MilesPerYear { get; set; }
        public Nullable<bool> AdjustMPY { get; set; }
        public Nullable<int> CurrentMiles { get; set; }
        public Nullable<System.DateTime> CurrentMilesDate { get; set; }
        public Nullable<int> PreviousOwners { get; set; }
        public string SMS { get; set; }
        public Nullable<bool> IsPublic { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Fuel> Fuels { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<OdometerHistory> OdometerHistories { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
