//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel
    {
        public int FuelID { get; set; }
        public int CarID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> BeginOdo { get; set; }
        public Nullable<double> EndOdo { get; set; }
        public Nullable<double> Miles { get; set; }
        public Nullable<double> Gallons { get; set; }
        public Nullable<decimal> MoneySpent { get; set; }
        public string Comments { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
