//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueItem
    {
        public int IssueItemID { get; set; }
        public int IssueID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> MaintenanceID { get; set; }
        public string JobDescr { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsMaintenance { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Job Job { get; set; }
        public virtual Maintenance Maintenance { get; set; }
    }
}
