//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public Issue()
        {
            this.IssueItems = new HashSet<IssueItem>();
        }
    
        public int IssueID { get; set; }
        public int CarID { get; set; }
        public string IssueName { get; set; }
        public string IssueDescr { get; set; }
        public Nullable<bool> IsResolved { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual ICollection<IssueItem> IssueItems { get; set; }
    }
}
