//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public Maintenance()
        {
            this.IssueItems = new HashSet<IssueItem>();
        }
    
        public int MaintenanceID { get; set; }
        public int CarID { get; set; }
        public int JobID { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> MileageDueNext { get; set; }
        public Nullable<System.DateTime> DateDueNext { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> WarningEmailSent { get; set; }
        public Nullable<System.DateTime> OverdueEmailSent { get; set; }
        public Nullable<bool> IgnoreWarning { get; set; }
        public Nullable<bool> IgnoreOverdue { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual ICollection<IssueItem> IssueItems { get; set; }
        public virtual Job Job { get; set; }
    }
}
