//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteID { get; set; }
        public int CarID { get; set; }
        public string NoteTitle { get; set; }
        public string NoteText { get; set; }
        public Nullable<int> MaintenanceID { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
