//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectItems = new HashSet<ProjectItem>();
        }
    
        public int ProjectID { get; set; }
        public int CarID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescr { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public bool Completed { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual ICollection<ProjectItem> ProjectItems { get; set; }
    }
}
