//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectItem
    {
        public int ProjectItemID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string ProjectItemName { get; set; }
        public string ProjectItemDescription { get; set; }
        public string Vendor { get; set; }
        public string PartNumber { get; set; }
        public string Link { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> Purchased { get; set; }
        public Nullable<bool> Shared { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<bool> Installed { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
