//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        public int ShoppingListID { get; set; }
        public int JobID { get; set; }
        public string ItemDescription { get; set; }
        public string ItemLink { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
