//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsernameQuery
    {
        public int UsernameQueryID { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> QueryDate { get; set; }
        public string IP { get; set; }
    }
}
