//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcptouch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Articles = new HashSet<Article>();
            this.Cars = new HashSet<Car>();
            this.LoginHistories = new HashSet<LoginHistory>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int NotificationDays { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Referral { get; set; }
        public string InitialIP { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<LoginHistory> LoginHistories { get; set; }
    }
}
